document.addEventListener('DOMContentLoaded', function() {
    const generateBtn = document.getElementById('generateBtn');
    const foodIcon = document.querySelector('.food-icon');
    const foodName = document.querySelector('.food-name');
    const lunchDisplay = document.querySelector('.lunch-display');
    
    // Array of lunch options: Font Awesome icons (free set) or a downloaded SVG image
    const lunchMenu = [
        { name: "Pizza", faClass: "fa-pizza-slice" },
        { name: "Sushi", faClass: "fa-fish" },
        { name: "Burger", faClass: "fa-hamburger" },
        { name: "Salad", faClass: "fa-leaf" },
        { name: "Tacos", img: "icons/taco.svg" },
        { name: "Ramen", img: "icons/ramen.svg" },
        { name: "Sandwich", faClass: "fa-bread-slice" },
        { name: "Pasta", img: "icons/pasta.svg" },
        { name: "Curry", faClass: "fa-mortar-pestle" },
        { name: "Steak", faClass: "fa-drumstick-bite" },
        { name: "Soup", img: "icons/soup.svg" },
        { name: "BBQ", faClass: "fa-fire" }
    ];

    // Seconds a dish stays blocked after being recommended
    const cooldownSeconds = 30;
    // Seconds the user must wait before restarting the randomizer (anti-spam)
    const clickCooldownSeconds = 20;
    // Last recommendation time per dish index (0 = never recommended)
    const lastRecommendedAt = new Array(lunchMenu.length).fill(0);
    // Last successful generation time (0 = not generated by user yet)
    let lastClickAt = 0;
    
    // Function to generate random lunch
    function generateRandomLunch() {
        // Remove fade-in class if it exists
        lunchDisplay.classList.remove('fade-in');
        
        // Pick a random lunch option that was not recommended in the last cooldown
        const now = Date.now();
        let eligible = [];
        lunchMenu.forEach((dish, index) => {
            if (now - lastRecommendedAt[index] >= cooldownSeconds * 1000) {
                eligible.push(index);
            }
        });
        
        // If every dish is still cooling down, pick the least recently recommended one
        if (eligible.length === 0) {
            let oldestIndex = 0;
            for (let i = 1; i < lastRecommendedAt.length; i++) {
                if (lastRecommendedAt[i] < lastRecommendedAt[oldestIndex]) {
                    oldestIndex = i;
                }
            }
            eligible = [oldestIndex];
        }
        
        const randomIndex = eligible[Math.floor(Math.random() * eligible.length)];
        const selectedLunch = lunchMenu[randomIndex];
        lastRecommendedAt[randomIndex] = now;
        
        // Briefly show loading state
        foodIcon.innerHTML = '<i class="fas fa-spinner fa-spin"></i>';
        foodName.textContent = "Thinking...";
        
        // After a short delay, show the selected lunch
        setTimeout(() => {
            if (selectedLunch.faClass) {
                foodIcon.innerHTML = `<i class="fas ${selectedLunch.faClass}"></i>`;
            } else {
                foodIcon.innerHTML = `<img src="${selectedLunch.img}" alt="${selectedLunch.name}">`;
            }
            foodName.textContent = selectedLunch.name;
            
            // Add animation class
            lunchDisplay.classList.add('fade-in');
        }, 500);
    }
    
    // Add click event to button
    generateBtn.addEventListener('click', function() {
        const now = Date.now();
        if (now - lastClickAt < clickCooldownSeconds * 1000) {
            foodIcon.innerHTML = '<i class="fas fa-hourglass-half"></i>';
            foodName.textContent = "Calm down, wait 20 seconds to restart the randomizer.";
            return;
        }
        lastClickAt = now;
        generateRandomLunch();
    });
    
    // Generate a random lunch on page load
    generateRandomLunch();
});